### ISSUE TITLE
Does not compile on newer node versions

### ISSUE THREAD

**Issue by TripleSpeeder** [TripleSpeeder/ens-updater#44]
installation fails at scrypt/node-gyp reinstall step with node versions:
- 13.1
- 12.13

Installation succeeds on 10.16 and below.

**Comment by evertonfraga** [comment]
the issue is fixed in web3.js. 
please update your version and package-lock.json

https://github.com/ethereum/web3.js/issues/3181

**Comment by TripleSpeeder** [comment]
thanks for the pointer @evertonfraga ! Actually I think there are two problems at play: npm install bails out with a "maximum call stack size exceeded" error:

```
make: Verzeichnis „/home/michael/WebstormProjects/ens-updater/node_modules/scrypt/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/michael/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.4.3-arch1-1
gyp ERR! command "/home/michael/.nvm/versions/node/v12.13.0/bin/node" "/home/michael/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/michael/WebstormProjects/ens-updater/node_modules/scrypt
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! Maximum call stack size exceeded
```
I don't know why this is happening. But trying installation with yarn looks a bit better, at least there is no mysterious call stick size issue. But in the end it also fails at compilation of scrypt:

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/michael/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.4.3-arch1-1
gyp ERR! command "/home/michael/.nvm/versions/node/v12.13.0/bin/node" "/home/michael/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/michael/WebstormProjects/ens-updater/node_modules/scrypt
```

I think the root cause is not in ens-updater configuration itself, but some dependency pulls in scrypt package. I'll try to dig deeper when i find the time :-/
